### PR TITLE
fix(connection): fixed connection details issues

### LINKED ISSUE #758: [BUG]  The skip test connection value is not supported
### 🐛 What happened?

If you try to create a new connection resource with skip_test_connection = false when the skip_test_connection is allowed, the following error is thrown

Image

This should be the correct logical table which should be followed to validate skip test connection

Image

### 🔬 How to reproduce?

_No response_

### 🏗️ Code Sample / Log

resource "fabric_connection" "anonymous_web_conn" {
  display_name      = "anonymous_web_conn"
  connectivity_type = "ShareableCloud"
  privacy_level     = "Organizational"
  connection_details = {
    type            = "Web"
    creation_method = "Web"
    parameters = [
      {
        name  = "url"
        value = "<REDACTED>"
      }
    ]
  }
  credential_details = {
    credential_type       = "Anonymous"
    skip_test_connection  = false
    anonymous_credentials = {}
  }
}

### 📷 Screenshots

_No response_

### 📈 Expected behavior

_No response_

### 🌌 Environment (Provider Version)

1.6

### 🌌 Environment (Terraform Version)

1.13.3

### 🌌 Environment (OS)

Windows

### 📎 Additional context

_No response_

### 🔰 Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

### PR DESCRIPTION
**Pull request by CatalinDabuleanu**
# 📥 Pull Request

## ❓ What are you trying to address

Fixed validation for `skip_test_connection` to allow users to perform test connection when skipping connection test is allowed
Updated Shared Access Signature properties names to match model 

This closes #758

### CODE REVIEW

File: internal/services/connection/models.go [hunk 1]
```diff
@@ -151,6 +151,6 @@ type credentialsServicePrincipalModel struct {
 }
 
 type credentialsSharedAccessSignatureModel struct {
-	TokenWO        types.String `tfsdk:"token_wo"`
-	TokenWOVersion types.Int32  `tfsdk:"token_wo_version"`
+	TokenWO        types.String `tfsdk:"sas_wo"`
```
Comment (badeamarjieh) [inline internal/services/connection/models.go]: what is this change?

Comment (OrBaubergMicrosoft) [reply internal/services/connection/models.go]: Basically, 
this pr solves two independent bugs
1. connection skip tests validation
2. documentation bug - we are documenting in case of credentialsSharedAccessSignature authentication, we documented  sas instead of token  

this change regards the second bug

**Comment by OrBaubergMicrosoft** [comment]
please add second bug fix to pr description

**Comment by OrBaubergMicrosoft** [comment]
are there any other schema - model misalignments?
